#!/bin/bash

readonly min_version=6.3
readonly scripts_repo_dir="usr/local/bin"
readonly scripts_install_dir="/usr/local/bin"

current_version=$(uname -r | cut -c1-3)

if [ "$EUID" -ne 0 ]
  then printf "Please run as root"
  exit
fi

install(){

  cp etc/systemd/system/powermanage.service /etc/systemd/system/

  cp "$scripts_repo_dir"/service_script "$scripts_install_dir"
  cp "$scripts_repo_dir"/unplugged_script "$scripts_install_dir"
  cp "$scripts_repo_dir"/plugged_script "$scripts_install_dir"

  chmod +x "$scripts_install_dir"/service_script
  chmod +x "$scripts_install_dir"/unplugged_script
  chmod +x "$scripts_install_dir"/plugged_script

  cp etc/udev/rules.d/pwr_management.rules /etc/udev/rules.d/

  systemctl enable --now powermanage.service

  udevadm control --reload

  printf "Installed correctly"
}

if (( $(echo "$current_version >= $min_version" |bc -l ))); then
  install
else
  while true; do

    printf "Do you have a kernel patched with amd-pstate epp (y/n)? "
    read -r answer
  if [[ ! ${answer,,} =~ ^y(es)?$ ]] ; then 

    install
    break 
  elif [[ ! ${answer,,} =~ ^n(o)?$ ]] ; then 

    printf "amd-pstate epp is a requirement for this script"
    break
  fi

  printf "Answer y/n \n" 
  done
fi