#!/bin/bash
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

cp usr/local/bin/unplugged_script /usr/local/bin/
cp usr/local/bin/plugged_script /usr/local/bin/
cp etc/udev/rules.d/pwr_management.rules /etc/udev/rules.d/
chmod +x /usr/local/bin/unplugged_script
chmod +x /usr/local/bin/plugged_script
udevadm control --reload
