#!/bin/bash

readonly scripts_install_dir="/usr/local/bin"

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

systemctl stop cpupower.service

rm /etc/systemd/system/cpupower.service

rm "$scripts_install_dir"/unplugged_script
rm "$scripts_install_dir"/plugged_script
rm "$scripts_install_dir"/service_script

rm /etc/udev/rules.d/pwr_management.rules

udevadm control --reload